### ISSUE TITLE
Mark Assignment 5 for Laura Z

### ISSUE THREAD

**Issue by lzgles** [lzgles/week_05#1]
210cc5d

@rharrington31

**Comment by rharrington31** [comment]
Overall, good! A couple of small comments:

For question 1, you could have simply done `read_csv(url)` instead of copying the `url` in.

For question 4, it would have been easier to identify which columns you _aren't_ pivoting instead of the ones that you are (`cols = c(-FIPS, -County, -Province_State, -Population)`).
